UA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("main.urls")),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

    path("", views.index, name="index"),

]

main/models.py
from django.db import models
import idna

# Create your models here.


class Person(models.Model):

    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_email(self):

         # spliting the email into parts
        email_parts = self.email.split("@")

        # decoding the email parts
        decoded_parts = tuple(
            map(
                idna.decode, email_parts
            )
        )

        # Joining the decoded email parts with "@" as the glue
        decoded_email = "@".join(decoded_parts)

        return decoded_email

    @staticmethod
    def is_valid_email(email):

        parts = email.split("@")

        if len(parts) == 2 and all(parts):

            second_part = parts[1]
            pieces = second_part.split(".")

            if len(pieces) >= 2 and all(pieces):
                return True

    def save(self, *args, **kwargs):

        email = self.email

        if Person.is_valid_email(email):

            # spliting the email into parts
            email_parts = email.split("@")

            # encoding the email parts
            encoded_parts = tuple(
                map(
                    # `bytes_object.decode("utf-8")` is used to convert
                    # bytes object to string object

                    lambda string: idna.encode(string).decode("utf-8"),
                    email_parts
                )
            )

            # Joining the encoded email parts with "@" as the glue
            encoded_email = "@".join(encoded_parts)

            # replacing the old email(not encoded)
            # with new email(encoded)
            self.email = encoded_email

            # saving
            return super().save(*args, **kwargs)

        # Raising error as the email is not valid
        raise ValueError("Invalid e-mail provided")

main/forms.py
from django import forms

class RegisterForm(forms.Form):

    email = forms.CharField(widget=forms.TextInput(
        attrs={
            'type': 'text'
        }
    ))
    name = forms.CharField()
    password = forms.CharField(widget=forms.TextInput(
        attrs={
            'type': 'password'
        }
    ))

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms as custom_forms
from .models import Person

# Create your views here.


def index(request):

    form = custom_forms.RegisterForm()
    is_email_valid = True

    if request.method == "POST":

        form = custom_forms.RegisterForm(request.POST)

        if form.is_valid():

            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]

            try:
                person = Person.objects.create(
                    name=name,
                    email=email,
                    password=password,
                )

                person.save()

                return render(request, "main/home.html", {
                    "person": person
                })

            except ValueError:
                is_email_valid = False

        else:
           is_email_valid = False

    return render(request, "main/index.html", {
        "form": form,
        "is_email_valid": is_email_valid,
    })

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> {% block title %} Welcome {% endblock title %} - UA</title>
    <link async rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link async rel="stylesheet" href="{% static 'main/main.css' %}">

    <meta name="description" content="An application that accepts, validate, process and store data provided by the user, data can be in any vernacular language." />
    <meta name="theme-color" content="#2E7D32" />

</head>
<body>

    <header>
        <nav class="green darken-3" >
            <div class="nav-wrapper center-align">
                <a href="#" class="brand-logo">UA</a>
            </div>
        </nav>
    </header>

    <main>
        {% block main %}{% endblock main %}
    </main>

    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %} Welcome {% endblock title %}

{% block main %}

    <section class="section">
        <div class="container">
            <div class="row">
                <div class="col s12 m6 offset-m3">
                    <div class="card-panel z-depth-0 text-darken-4">
                   
                        <h4 class="center heading-h4">Welcome</h4>

                        <div class="card green darken-3">
                            <div class="card-content white-text">
                                <span class="card-title"> {{person.name}} </span>
                                <p> {{person.get_email}} </p>
                            </div>
                        </div>
                    </div>

                    <div class="center-align">
                        <a href={% url 'main:index' %} class='btn-small green darken-3 waves-effect'> 
                            back to signup
                        </a>
                    </div>

                </div>
            </divx> 
        </div>
    </section>

{% endblock main %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %} Signup {% endblock title %}

{% block main %}

    <section class="section section-signup">
        <div class="container">
            <div class="row">
                <div class=" col s12 m6 offset-m3">
                    <div class="card-panel">
                        
                        <h4 class="center heading-h4">Signup</h4>
                        
                        <form method="POST">

                            {% csrf_token %}

                            {% if not is_email_valid %}
                                <span class="red-text"> सही ईमेल प्रदान करे।  </span>
                            {% endif %}
                            
                            <div class="input-field">
                                {{form.email}}
                                {{form.email.label_tag}}
                            </div>

                            <div class="input-field">
                                {{form.name}}
                                {{form.name.label_tag}}
                            </div>

                            <div class="input-field">
                                {{form.password}}
                                {{form.password.label_tag}}
                            </div>
                            
                            <div class="center-align">
                                <button type="submit" class="btn btn-small green darken-3"> join </button>
                            </div>

                        </form>
                    </div>
                </div>
            </divx>
        </div>
    </section>

{% endblock main %}